# Generated by Django 5.1.1 on 2024-10-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='accent',
            field=models.CharField(default='accesnt', max_length=200),
        ),
        migrations.AddField(
            model_name='visitors',
            name='language',
            field=models.CharField(default='language', max_length=200),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='text',
            field=models.CharField(default='text', max_length=2000),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='title',
            field=models.CharField(default='tit;e', max_length=200),
        ),
    ]
